### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by NicoGonzalez94** [FT-Key/RollingVetBackend#20]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/user-attachments/assets/278e8f27-ff1f-49a7-919d-f448cd3fcd91)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FT-Key** [comment]
Listo, código limpiado, solo dejé comentarios significativos donde el código se torna menos intuitivo y donde ayudan a mantener el código más ordenado (cuidado al buscar "//", porque tambien aparecen todas las url de por ejemplo, arrays que sirven para poblar la base de datos para la presentación y prueba de la página)
